In [155]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [156]:
movies = pd.read_csv("data/movies.csv")
credits = pd.read_csv("data/credits.csv")

In [157]:
pd.set_option("display.max_columns", 80)
pd.set_option("display.max_rows", 80)

In [158]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [159]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [160]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [161]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [162]:
credits = credits.rename(columns={'movie_id': 'id'})

In [163]:
merged_data = movies.merge(credits, on= "id")

In [164]:
merged_data.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title_x,vote_average,vote_count,title_y,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [165]:
merged_data.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'title_y', 'cast', 'crew'],
      dtype='str')

In [166]:
merged_data.rename(columns={"title_x": "title"}, inplace=True)

In [167]:
merged_data.shape

(4803, 23)

In [168]:
movies = merged_data.head(1500)

In [169]:
movies.shape

(1500, 23)

In [170]:
movies = movies[['id', 'title', 'overview', 'genres', 'keywords',  'cast', 'crew']]

In [171]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [172]:
movies.shape

(1500, 7)

In [173]:
movies.isna().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [174]:
movies.duplicated().sum()

np.int64(0)

In [175]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [176]:
import json
def convert(obj):
    return [i['name'] for i in json.loads(obj)]

In [177]:
movies["genres"] = movies.genres.apply(convert)
movies["keywords"] = movies.keywords.apply(convert)

In [178]:
movies.head()

,id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [179]:
movies.iloc[0].cast

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [180]:
def first_five(obj):
    return[i['name'] for i in json.loads(obj)[:5]]

In [181]:
movies['cast'] = movies.cast.apply(first_five)
print(movies.iloc[0].cast)

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang', 'Michelle Rodriguez']

In [182]:
v = movies.iloc[0].crew
c = json.loads(v)
job = [i['name'] for i in c if i['job'] == "Director"]
print(job)

['James Cameron']

In [183]:
def pick_director(obj):
    return [i['name'] for i in json.loads(obj) if i['job'] == "Director"]

In [184]:
movies['director'] = movies.crew.apply(pick_director)
movies.head()

,id,title,overview,genres,keywords,cast,crew,director
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[Andrew Stanton]

In [185]:
movies.drop(columns=["crew" , "overview"], inplace=True)
movies.head()

,id,title,genres,keywords,cast,director
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [186]:
def remove_spaces(obj):
    return [i.replace(" ", "") for i in obj]

In [187]:
movies ['genres'] = movies.genres.apply(remove_spaces)
movies ['keywords'] = movies.keywords.apply(remove_spaces)
movies ['cast'] = movies.cast.apply(remove_spaces)
movies ['director'] = movies.director.apply(remove_spaces)

In [188]:
movies.head(1)

,id,title,genres,keywords,cast,director
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]

In [189]:
movies['tags'] = movies['genres'] + movies['keywords'] + movies['cast'] + movies['director']

In [190]:
movies.head(1)

,id,title,genres,keywords,cast,director,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[Action, Adventure, Fantasy, ScienceFiction, c..."

In [191]:
new_df = movies[["id", "title", "tags"]]

In [192]:
new_df.head()

,id,title,tags
0,19995,Avatar,"[Action, Adventure, Fantasy, ScienceFiction, c..."
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action, ocean, drugabuse,..."
2,206647,Spectre,"[Action, Adventure, Crime, spy, basedonnovel, ..."
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller, dccomics, cri..."
4,49529,John Carter,"[Action, Adventure, ScienceFiction, basedonnov..."

In [193]:
new_df['tags'] = new_df['tags'].apply(lambda x :" ".join(x).lower())

In [194]:
new_df.head(1)

      id   title                                               tags
0  19995  Avatar  action adventure fantasy sciencefiction cultur...

#### training

In [195]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stemming_words(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)
new_df['tags_stemmed'] = new_df['tags'].apply(stemming_words)

In [201]:
from IPython.display import display, HTML

def highlight_changes_html(x, y):
    o = x.split()
    st = y.split()
    
    result = []
    
    for i in range(min(len(o), len(st))):
        if o[i] != st[i]:
            result.append(
                f"<span style='color:red;font-weight:bold'>{o[i]} → {st[i]}</span>"
            )
        else:
            result.append(o[i])
    
    # extra words in original
    if len(o) > len(st):
        for i in range(len(st), len(o)):
            result.append(
                f"<span style='color:red;font-weight:bold'>{o[i]} → removed</span>"
            )
    
    # extra words in stemmed
    if len(st) > len(o):
        for i in range(len(o), len(st)):
            result.append(
                f"<span style='color:red;font-weight:bold'>missing → {st[i]}</span>"
            )
    
    return " ".join(result)

In [202]:
new_df['highlight_diff'] = new_df.apply(
    lambda row: highlight_changes_html(row['tags'], row['tags_stemmed']),
    axis=1
)

In [203]:
for i in range(5):
    display(HTML(new_df['highlight_diff'].iloc[i]))

In [204]:
new_df.head(1)

,id,title,tags,tags_stemmed,diff,highlight_diff
0,19995,Avatar,action adventure fantasy sciencefiction cultur...,action adventur fantasi sciencefict culturecla...,"adventure → adventur, fantasy → fantasi, scien...",action <span style='color:red;font-weight:bold...

In [206]:
new_df = new_df[['id', 'title', 'tags_stemmed']]

In [207]:
new_df.head(1)

      id   title                                       tags_stemmed
0  19995  Avatar  action adventur fantasi sciencefict culturecla...

In [208]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [209]:
vectors = cv.fit_transform(new_df['tags_stemmed']).toarray()

In [210]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1500, 5000))

In [213]:
from sklearn.metrics.pairwise import cosine_similarity
similar = cosine_similarity(vectors)

In [214]:
similar.shape

(1500, 1500)

In [216]:
similar[0]

array([1.        , 0.10741723, 0.0942809 , ..., 0.04428074, 0.        ,
       0.03806935], shape=(1500,))

In [217]:
sorted(list(enumerate(similar[0])), reverse=True, key=lambda x:x[1])

[(0, np.float64(0.9999999999999998)),
 (47, np.float64(0.34426518632954817)),
 (61, np.float64(0.2927700218845599)),
 (83, np.float64(0.27602622373694163)),
 (94, np.float64(0.2449489742783178)),
 (260, np.float64(0.2449489742783178)),
 (1191, np.float64(0.24397501823713327)),
 (1201, np.float64(0.23904572186687872)),
 (322, np.float64(0.23333333333333328)),
 (466, np.float64(0.2309401076758503)),
 (4, np.float64(0.2284160962880643)),
 (786, np.float64(0.223606797749979)),
 (1324, np.float64(0.223606797749979)),
 (81, np.float64(0.22140372138502382)),
 (661, np.float64(0.22140372138502382)),
 (17, np.float64(0.21908902300206642)),
 (41, np.float64(0.21516574145596762)),
 (168, np.float64(0.21516574145596762)),
 (507, np.float64(0.21516574145596762)),
 (838, np.float64(0.21483446221182984)),
 (490, np.float64(0.21081851067789198)),
 (1287, np.float64(0.21081851067789198)),
 (931, np.float64(0.20942695414584772)),
 (1390, np.float64(0.20942695414584772)),
 (108, np.float64(0.20412414523193148)),
 (206, np.float64(0.20412414523193148)),
 (50, np.float64(0.20254787341673333)),
 (56, np.float64(0.20254787341673333)),
 (495, np.float64(0.20254787341673333)),
 (859, np.float64(0.20254787341673333)),
 (1086, np.float64(0.20254787341673333)),
 (278, np.float64(0.19920476822239894)),
 (539, np.float64(0.19920476822239894)),
 (1044, np.float64(0.19518001458970663)),
 (1192, np.float64(0.19518001458970663)),
 (1213, np.float64(0.19518001458970663)),
 (85, np.float64(0.19462473604038072)),
 (1481, np.float64(0.19364916731037082)),
 (582, np.float64(0.19034674690672024)),
 (36, np.float64(0.18856180831641264)),
 (51, np.float64(0.18856180831641264)),
 (74, np.float64(0.18856180831641264)),
 (84, np.float64(0.18856180831641264)),
 (102, np.float64(0.18856180831641264)),
 (182, np.float64(0.18856180831641264)),
 (184, np.float64(0.18856180831641264)),
 (187, np.float64(0.18856180831641264)),
 (228, np.float64(0.18856180831641264)),
 (371, np.float64(0.18856180831641264)),
 (777, np.float64(0.18856180831641264)),
 (939, np.float64(0.18856180831641264)),
 (942, np.float64(0.18856180831641264)),
 (238, np.float64(0.18633899812498247)),
 (71, np.float64(0.18257418583505536)),
 (577, np.float64(0.18257418583505536)),
 (773, np.float64(0.18257418583505536)),
 (32, np.float64(0.17712297710801905)),
 (193, np.float64(0.17320508075688773)),
 (457, np.float64(0.17320508075688773)),
 (715, np.float64(0.17320508075688773)),
 (305, np.float64(0.17251638983558854)),
 (7, np.float64(0.17213259316477408)),
 (72, np.float64(0.17213259316477408)),
 (126, np.float64(0.17213259316477408)),
 (232, np.float64(0.17213259316477408)),
 (972, np.float64(0.17213259316477408)),
 (1230, np.float64(0.17213259316477408)),
 (10, np.float64(0.1675415633166782)),
 (14, np.float64(0.1675415633166782)),
 (111, np.float64(0.1675415633166782)),
 (172, np.float64(0.1675415633166782)),
 (870, np.float64(0.1675415633166782)),
 (91, np.float64(0.1651445647689541)),
 (208, np.float64(0.1651445647689541)),
 (315, np.float64(0.1651445647689541)),
 (379, np.float64(0.1651445647689541)),
 (486, np.float64(0.1651445647689541)),
 (1303, np.float64(0.1651445647689541)),
 (46, np.float64(0.1632993161855452)),
 (52, np.float64(0.1632993161855452)),
 (127, np.float64(0.1632993161855452)),
 (151, np.float64(0.1632993161855452)),
 (587, np.float64(0.1632993161855452)),
 (754, np.float64(0.1632993161855452)),
 (799, np.float64(0.1632993161855452)),
 (1296, np.float64(0.1632993161855452)),
 (19, np.float64(0.15936381457791915)),
 (26, np.float64(0.15936381457791915)),
 (31, np.float64(0.15936381457791915)),
 (207, np.float64(0.15936381457791915)),
 (300, np.float64(0.15936381457791915)),
 (131, np.float64(0.158113883008419)),
 (294, np.float64(0.158113883008419)),
 (362, np.float64(0.158113883008419)),
 (412, np.float64(0.158113883008419)),
 (467, np.float64(0.158113883008419)),
 (535, np.float64(0.158113883008419)),
 (627, np.float64(0.158113883008419)),
 (1272, np.float64(0.158113883008419)),
 (1277, np.float64(0.158113883008419)),
 (1326, np.float64(0.158113883008419)),
 (304, np.float64(0.15811388300841897)),
 (129, np.float64(0.15569978883230456)),
 (160, np.float64(0.15569978883230456)),
 (166, np.float64(0.15569978883230456)),
 (169, np.float64(0.15569978883230456)),
 (266, np.float64(0.15569978883230456)),
 (342, np.float64(0.15569978883230456)),
 (1083, np.float64(0.15569978883230456)),
 (150, np.float64(0.1522773975253762)),
 (740, np.float64(0.1522773975253762)),
 (778, np.float64(0.1522773975253762)),
 (18, np.float64(0.15191090506255)),
 (38, np.float64(0.15191090506255)),
 (86, np.float64(0.15191090506255)),
 (97, np.float64(0.15191090506255)),
 (157, np.float64(0.15191090506255)),
 (241, np.float64(0.15191090506255)),
 (413, np.float64(0.15191090506255)),
 (472, np.float64(0.15191090506255)),
 (541, np.float64(0.15191090506255)),
 (581, np.float64(0.15191090506255)),
 (791, np.float64(0.15191090506255)),
 (814, np.float64(0.15191090506255)),
 (836, np.float64(0.15191090506255)),
 (999, np.float64(0.15191090506255)),
 (1093, np.float64(0.15191090506255)),
 (1319, np.float64(0.15191090506255)),
 (1395, np.float64(0.15191090506255)),
 (1473, np.float64(0.15191090506255)),
 (158, np.float64(0.14907119849998599)),
 (813, np.float64(0.14907119849998599)),
 (67, np.float64(0.14638501094227996)),
 (70, np.float64(0.14638501094227996)),
 (292, np.float64(0.14638501094227996)),
 (400, np.float64(0.14638501094227996)),
 (487, np.float64(0.14638501094227996)),
 (505, np.float64(0.14638501094227996)),
 (511, np.float64(0.14638501094227996)),
 (543, np.float64(0.14638501094227996)),
 (660, np.float64(0.14638501094227996)),
 (935, np.float64(0.14638501094227996)),
 (1001, np.float64(0.14638501094227996)),
 (1028, np.float64(0.14638501094227996)),
 (1438, np.float64(0.14638501094227996)),
 (1490, np.float64(0.14638501094227996)),
 (1491, np.float64(0.14638501094227996)),
 (149, np.float64(0.1460593486680443)),
 (501, np.float64(0.1460593486680443)),
 (28, np.float64(0.14322297480788657)),
 (55, np.float64(0.14322297480788657)),
 (654, np.float64(0.14322297480788657)),
 (1291, np.float64(0.14322297480788657)),
 (39, np.float64(0.14142135623730948)),
 (59, np.float64(0.14142135623730948)),
 (121, np.float64(0.14142135623730948)),
 (203, np.float64(0.14142135623730948)),
 (224, np.float64(0.14142135623730948)),
 (307, np.float64(0.14142135623730948)),
 (389, np.float64(0.14142135623730948)),
 (612, np.float64(0.14142135623730948)),
 (643, np.float64(0.14142135623730948)),
 (732, np.float64(0.14142135623730948)),
 (746, np.float64(0.14142135623730948)),
 (781, np.float64(0.14142135623730948)),
 (898, np.float64(0.14142135623730948)),
 (976, np.float64(0.14142135623730948)),
 (1110, np.float64(0.14142135623730948)),
 (1495, np.float64(0.14142135623730948)),
 (491, np.float64(0.1405456737852613)),
 (1433, np.float64(0.1405456737852613)),
 (678, np.float64(0.13801311186847082)),
 (1068, np.float64(0.13801311186847082)),
 (1079, np.float64(0.13801311186847082)),
 (1306, np.float64(0.13801311186847082)),
 (1453, np.float64(0.13801311186847082)),
 (9, np.float64(0.13693063937629152)),
 (79, np.float64(0.13693063937629152)),
 (233, np.float64(0.13693063937629152)),
 (249, np.float64(0.13693063937629152)),
 (295, np.float64(0.13693063937629152)),
 (311, np.float64(0.13693063937629152)),
 (589, np.float64(0.13693063937629152)),
 (607, np.float64(0.13693063937629152)),
 (624, np.float64(0.13693063937629152)),
 (665, np.float64(0.13693063937629152)),
 (768, np.float64(0.13693063937629152)),
 (920, np.float64(0.13693063937629152)),
 (1139, np.float64(0.13693063937629152)),
 (1153, np.float64(0.13693063937629152)),
 (1155, np.float64(0.13693063937629152)),
 (1175, np.float64(0.13693063937629152)),
 (1199, np.float64(0.13693063937629152)),
 (1266, np.float64(0.13693063937629152)),
 (618, np.float64(0.13561270072416207)),
 (33, np.float64(0.1328422328310143)),
 (35, np.float64(0.1328422328310143)),
 (132, np.float64(0.1328422328310143)),
 (279, np.float64(0.1328422328310143)),
 (332, np.float64(0.1328422328310143)),
 (368, np.float64(0.1328422328310143)),
 (420, np.float64(0.1328422328310143)),
 (728, np.float64(0.1328422328310143)),
 (977, np.float64(0.1328422328310143)),
 (1198, np.float64(0.1328422328310143)),
 (1399, np.float64(0.1328422328310143)),
 (190, np.float64(0.12909944487358058)),
 (20, np.float64(0.12909944487358055)),
 (30, np.float64(0.12909944487358055)),
 (37, np.float64(0.12909944487358055)),
 (101, np.float64(0.12909944487358055)),
 (122, np.float64(0.12909944487358055)),
 (220, np.float64(0.12909944487358055)),
 (229, np.float64(0.12909944487358055)),
 (373, np.float64(0.12909944487358055)),
 (403, np.float64(0.12909944487358055)),
 (483, np.float64(0.12909944487358055)),
 (508, np.float64(0.12909944487358055)),
 (671, np.float64(0.12909944487358055)),
 (922, np.float64(0.12909944487358055)),
 (960, np.float64(0.12909944487358055)),
 (1016, np.float64(0.12909944487358055)),
 (1099, np.float64(0.12909944487358055)),
 (1273, np.float64(0.12909944487358055)),
 (1309, np.float64(0.12909944487358055)),
 (1322, np.float64(0.12909944487358055)),
 (1468, np.float64(0.12909944487358055)),
 (16, np.float64(0.12565617248750865)),
 (68, np.float64(0.12565617248750865)),
 (96, np.float64(0.12565617248750865)),
 (138, np.float64(0.12565617248750865)),
 (174, np.float64(0.12565617248750865)),
 (419, np.float64(0.12565617248750865)),
 (547, np.float64(0.12565617248750865)),
 (1377, np.float64(0.12565617248750865)),
 (503, np.float64(0.12565617248750863)),
 (183, np.float64(0.12524485821702988)),
 (242, np.float64(0.1224744871391589)),
 (334, np.float64(0.1224744871391589)),
 (369, np.float64(0.1224744871391589)),
 (579, np.float64(0.1224744871391589)),
 (657, np.float64(0.1224744871391589)),
 (1080, np.float64(0.1224744871391589)),
 (1337, np.float64(0.1224744871391589)),
 (95, np.float64(0.1217161238900369)),
 (125, np.float64(0.1217161238900369)),
 (302, np.float64(0.1217161238900369)),
 (381, np.float64(0.1217161238900369)),
 (1259, np.float64(0.1217161238900369)),
 (1290, np.float64(0.1217161238900369)),
 (1447, np.float64(0.1217161238900369)),
 (1474, np.float64(0.1217161238900369)),
 (43, np.float64(0.11952286093343936)),
 (88, np.float64(0.11952286093343936)),
 (107, np.float64(0.11952286093343936)),
 (112, np.float64(0.11952286093343936)),
 (271, np.float64(0.11952286093343936)),
 (275, np.float64(0.11952286093343936)),
 (572, np.float64(0.11952286093343936)),
 (591, np.float64(0.11952286093343936)),
 (1143, np.float64(0.11952286093343936)),
 (1294, np.float64(0.11952286093343936)),
 (1341, np.float64(0.11952286093343936)),
 (27, np.float64(0.11677484162422842)),
 (270, np.float64(0.11677484162422842)),
 (426, np.float64(0.11677484162422842)),
 (48, np.float64(0.11547005383792515)),
 (75, np.float64(0.11547005383792515)),
 (471, np.float64(0.11547005383792515)),
 (479, np.float64(0.11547005383792515)),
 (518, np.float64(0.11547005383792515)),
 (534, np.float64(0.11547005383792515)),
 (600, np.float64(0.11547005383792515)),
 (610, np.float64(0.11547005383792515)),
 (776, np.float64(0.11547005383792515)),
 (1002, np.float64(0.11547005383792515)),
 (1289, np.float64(0.11547005383792515)),
 (12, np.float64(0.11420804814403215)),
 (25, np.float64(0.11420804814403215)),
 (63, np.float64(0.11420804814403215)),
 (230, np.float64(0.11420804814403215)),
 (510, np.float64(0.11420804814403215)),
 (755, np.float64(0.11420804814403215)),
 (937, np.float64(0.11420804814403215)),
 (1012, np.float64(0.11420804814403215)),
 (1034, np.float64(0.11420804814403215)),
 (1439, np.float64(0.11420804814403215)),
 (5, np.float64(0.1118033988749895)),
 (82, np.float64(0.1118033988749895)),
 (329, np.float64(0.1118033988749895)),
 (900, np.float64(0.1118033988749895)),
 (309, np.float64(0.11009637651263605)),
 (458, np.float64(0.11009637651263605)),
 (461, np.float64(0.11009637651263605)),
 (476, np.float64(0.11009637651263605)),
 (530, np.float64(0.11009637651263605)),
 (595, np.float64(0.11009637651263605)),
 (674, np.float64(0.11009637651263605)),
 (831, np.float64(0.11009637651263605)),
 (989, np.float64(0.11009637651263605)),
 (1246, np.float64(0.11009637651263605)),
 (1270, np.float64(0.11009637651263605)),
 (1274, np.float64(0.11009637651263605)),
 (1298, np.float64(0.11009637651263605)),
 (1320, np.float64(0.11009637651263605)),
 (1428, np.float64(0.11009637651263605)),
 (92, np.float64(0.10954451150103323)),
 (103, np.float64(0.10954451150103323)),
 (199, np.float64(0.10954451150103323)),
 (243, np.float64(0.10954451150103323)),
 (410, np.float64(0.10954451150103323)),
 (123, np.float64(0.10886621079036347)),
 (1, np.float64(0.10741723110591492)),
 (76, np.float64(0.10741723110591492)),
 (262, np.float64(0.10741723110591492)),
 (330, np.float64(0.10741723110591492)),
 (98, np.float64(0.10540925533894599)),
 (147, np.float64(0.10540925533894599)),
 (189, np.float64(0.10540925533894599)),
 (205, np.float64(0.10540925533894599)),
 (219, np.float64(0.10540925533894599)),
 (222, np.float64(0.10540925533894599)),
 (239, np.float64(0.10540925533894599)),
 (253, np.float64(0.10540925533894599)),
 (306, np.float64(0.10540925533894599)),
 (308, np.float64(0.10540925533894599)),
 (312, np.float64(0.10540925533894599)),
 (319, np.float64(0.10540925533894599)),
 (340, np.float64(0.10540925533894599)),
 (363, np.float64(0.10540925533894599)),
 (375, np.float64(0.10540925533894599)),
 (540, np.float64(0.10540925533894599)),
 (602, np.float64(0.10540925533894599)),
 (668, np.float64(0.10540925533894599)),
 (800, np.float64(0.10540925533894599)),
 (888, np.float64(0.10540925533894599)),
 (894, np.float64(0.10540925533894599)),
 (984, np.float64(0.10540925533894599)),
 (1000, np.float64(0.10540925533894599)),
 (1008, np.float64(0.10540925533894599)),
 (1082, np.float64(0.10540925533894599)),
 (1137, np.float64(0.10540925533894599)),
 (1183, np.float64(0.10540925533894599)),
 (1256, np.float64(0.10540925533894599)),
 (1271, np.float64(0.10540925533894599)),
 (1448, np.float64(0.10540925533894599)),
 (1482, np.float64(0.10540925533894599)),
 (11, np.float64(0.10127393670836667)),
 (44, np.float64(0.10127393670836667)),
 (49, np.float64(0.10127393670836667)),
 (62, np.float64(0.10127393670836667)),
 (148, np.float64(0.10127393670836667)),
 (153, np.float64(0.10127393670836667)),
 (167, np.float64(0.10127393670836667)),
 (170, np.float64(0.10127393670836667)),
 (223, np.float64(0.10127393670836667)),
 (237, np.float64(0.10127393670836667)),
 (257, np.float64(0.10127393670836667)),
 (259, np.float64(0.10127393670836667)),
 (411, np.float64(0.10127393670836667)),
 (604, np.float64(0.10127393670836667)),
 (691, np.float64(0.10127393670836667)),
 (731, np.float64(0.10127393670836667)),
 (735, np.float64(0.10127393670836667)),
 (752, np.float64(0.10127393670836667)),
 (993, np.float64(0.10127393670836667)),
 (1053, np.float64(0.10127393670836667)),
 (1074, np.float64(0.10127393670836667)),
 (1085, np.float64(0.10127393670836667)),
 (1146, np.float64(0.10127393670836667)),
 (1204, np.float64(0.10127393670836667)),
 (1234, np.float64(0.10127393670836667)),
 (1245, np.float64(0.10127393670836667)),
 (1300, np.float64(0.10127393670836667)),
 (1380, np.float64(0.10127393670836667)),
 (1412, np.float64(0.10127393670836667)),
 (1422, np.float64(0.10127393670836667)),
 (1460, np.float64(0.10127393670836667)),
 (212, np.float64(0.09837387536759293)),
 (415, np.float64(0.09837387536759293)),
 (784, np.float64(0.09837387536759293)),
 (45, np.float64(0.09759000729485331)),
 (164, np.float64(0.09759000729485331)),
 (179, np.float64(0.09759000729485331)),
 (244, np.float64(0.09759000729485331)),
 (331, np.float64(0.09759000729485331)),
 (366, np.float64(0.09759000729485331)),
 (376, np.float64(0.09759000729485331)),
 (470, np.float64(0.09759000729485331)),
 (488, np.float64(0.09759000729485331)),
 (513, np.float64(0.09759000729485331)),
 (537, np.float64(0.09759000729485331)),
 (555, np.float64(0.09759000729485331)),
 (629, np.float64(0.09759000729485331)),
 (640, np.float64(0.09759000729485331)),
 (664, np.float64(0.09759000729485331)),
 (687, np.float64(0.09759000729485331)),
 (710, np.float64(0.09759000729485331)),
 (855, np.float64(0.09759000729485331)),
 (908, np.float64(0.09759000729485331)),
 (994, np.float64(0.09759000729485331)),
 (995, np.float64(0.09759000729485331)),
 (1017, np.float64(0.09759000729485331)),
 (1058, np.float64(0.09759000729485331)),
 (1134, np.float64(0.09759000729485331)),
 (1136, np.float64(0.09759000729485331)),
 (1217, np.float64(0.09759000729485331)),
 (1238, np.float64(0.09759000729485331)),
 (1239, np.float64(0.09759000729485331)),
 (1263, np.float64(0.09759000729485331)),
 (1279, np.float64(0.09759000729485331)),
 (1372, np.float64(0.09759000729485331)),
 (1440, np.float64(0.09759000729485331)),
 (812, np.float64(0.09682458365518541)),
 (1106, np.float64(0.09682458365518541)),
 (2, np.float64(0.09428090415820632)),
 (21, np.float64(0.09428090415820632)),
 (22, np.float64(0.09428090415820632)),
 (23, np.float64(0.09428090415820632)),
 (87, np.float64(0.09428090415820632)),
 (105, np.float64(0.09428090415820632)),
 (141, np.float64(0.09428090415820632)),
 (195, np.float64(0.09428090415820632)),
 (256, np.float64(0.09428090415820632)),
 (263, np.float64(0.09428090415820632)),
 (289, np.float64(0.09428090415820632)),
 (291, np.float64(0.09428090415820632)),
 (350, np.float64(0.09428090415820632)),
 (359, np.float64(0.09428090415820632)),
 (485, np.float64(0.09428090415820632)),
 (531, np.float64(0.09428090415820632)),
 (549, np.float64(0.09428090415820632)),
 (574, np.float64(0.09428090415820632)),
 (575, np.float64(0.09428090415820632)),
 (597, np.float64(0.09428090415820632)),
 (601, np.float64(0.09428090415820632)),
 (653, np.float64(0.09428090415820632)),
 (683, np.float64(0.09428090415820632)),
 (718, np.float64(0.09428090415820632)),
 (788, np.float64(0.09428090415820632)),
 (792, np.float64(0.09428090415820632)),
 (793, np.float64(0.09428090415820632)),
 (808, np.float64(0.09428090415820632)),
 (956, np.float64(0.09428090415820632)),
 (1084, np.float64(0.09428090415820632)),
 (1193, np.float64(0.09428090415820632)),
 (1318, np.float64(0.09428090415820632)),
 (1343, np.float64(0.09428090415820632)),
 (1344, np.float64(0.09428090415820632)),
 (1359, np.float64(0.09428090415820632)),
 (1367, np.float64(0.09428090415820632)),
 (1420, np.float64(0.09428090415820632)),
 (1494, np.float64(0.09428090415820632)),
 (215, np.float64(0.0939336436627724)),
 (8, np.float64(0.09128709291752768)),
 (90, np.float64(0.09128709291752768)),
 (117, np.float64(0.09128709291752768)),
 (134, np.float64(0.09128709291752768)),
 (143, np.float64(0.09128709291752768)),
 (175, np.float64(0.09128709291752768)),
 (216, np.float64(0.09128709291752768)),
 (341, np.float64(0.09128709291752768)),
 (358, np.float64(0.09128709291752768)),
 (422, np.float64(0.09128709291752768)),
 (443, np.float64(0.09128709291752768)),
 (449, np.float64(0.09128709291752768)),
 (480, np.float64(0.09128709291752768)),
 (492, np.float64(0.09128709291752768)),
 (523, np.float64(0.09128709291752768)),
 (544, np.float64(0.09128709291752768)),
 (546, np.float64(0.09128709291752768)),
 (568, np.float64(0.09128709291752768)),
 (609, np.float64(0.09128709291752768)),
 (621, np.float64(0.09128709291752768)),
 (675, np.float64(0.09128709291752768)),
 (775, np.float64(0.09128709291752768)),
 (816, np.float64(0.09128709291752768)),
 (833, np.float64(0.09128709291752768)),
 (850, np.float64(0.09128709291752768)),
 (1035, np.float64(0.09128709291752768)),
 (1361, np.float64(0.09128709291752768)),
 (1363, np.float64(0.09128709291752768)),
 (100, np.float64(0.08856148855400953)),
 (109, np.float64(0.08856148855400953)),
 (185, np.float64(0.08856148855400953)),
 (198, np.float64(0.08856148855400953)),
 (217, np.float64(0.08856148855400953)),
 (267, np.float64(0.08856148855400953)),
 (277, np.float64(0.08856148855400953)),
 (290, np.float64(0.08856148855400953)),

In [222]:
def recommend(movie):
    movie_index = new_df[new_df['title'].str.lower() == movie.lower()].index[0]
    distances = similar[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x : x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [224]:
recommend('avatar')

Star Trek Into Darkness
Jupiter Ascending
The Lovers
Guardians of the Galaxy
Ender's Game

In [225]:
import pickle
pickle.dump(new_df, open('movie.pkl', 'wb'))
pickle.dump(similar, open('similarity.pkl', 'wb'))

In [227]:
new_df.title.values

<ArrowStringArray>
[                                  'Avatar',
 'Pirates of the Caribbean: At World's End',
                                  'Spectre',
                    'The Dark Knight Rises',
                              'John Carter',
                             'Spider-Man 3',
                                  'Tangled',
                  'Avengers: Age of Ultron',
   'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice',
 ...
                       'Return of the Jedi',
                                 'Doomsday',
                               'The Reader',
                               'Wanderlust',
                                      'Elf',
                               'Phenomenon',
                                'Snow Dogs',
                                 'Scrooged',
                              'Nacho Libre',
                              'Bridesmaids']
Length: 1500, dtype: str

In [229]:
recommend("Avatar")

Star Trek Into Darkness
Jupiter Ascending
The Lovers
Guardians of the Galaxy
Ender's Game